# https://docs.travis-ci.com/user/reference/windows/
os: windows
language: bash  # language: java is not yet supported on Travis CI Windows
env: 
  - PACKAGE=adoptopenjdk8
  - PACKAGE=adoptopenjdk8jre
  - PACKAGE=adoptopenjdk11
  - PACKAGE=adoptopenjdk11jre
  - PACKAGE=adoptopenjdk
  - PACKAGE=adoptopenjdkjre
script:
  - powershell .travis.ps1 || true  # ignore the failure
  - powershell 'choco install $PACKAGE ; refreshenv ; echo $Env:Path ; java -version'
  - java -version || true  # ignore the failure
  
